FROM rust:latest as build

RUN apt-get update && apt-get install -y \
    libssl-dev \
    pkg-config \
    build-essential \
    cmake \
    curl \
    git 

RUN mkdir /app
WORKDIR /app

ADD truncate_server /app/truncate_server
ADD truncate_core /app/truncate_core

RUN cd truncate_server && cargo build --release

CMD truncate_server/target/release/truncate_server
