# Unified Truncate deployment
# prod:    fly deploy -a truncate
# staging: fly deploy -a truncate-exclave

kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "syd"

[build]
dockerfile = "Dockerfile"

[env]
STATIC_DIR = "/app/web_client"
TR_DEFS_FILE = "/truncate/defs.db"

[[services]]
internal_port = 8080
processes = ["app"]
protocol = "tcp"

[services.concurrency]
type = "connections"
hard_limit = 1000
soft_limit = 800

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443
