[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
    "apt-get install --assume-yes libudev-dev:$CROSS_DEB_ARCH",
]
[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
    "apt-get install --assume-yes libudev-dev:$CROSS_DEB_ARCH",
]
[target.arm-unknown-linux-gnueabihf]
# For https://github.com/cross-rs/cross/pull/1317
image = "ghcr.io/cross-rs/arm-unknown-linux-gnueabihf:edge"
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get clean",
    "apt-get update",
    "apt-get clean",
    "apt-get update",
    "apt-get clean",
    "cat /etc/apt/sources.list",
    "ldd --version",
    "apt-cache madison libudev-dev:$CROSS_DEB_ARCH",
    "apt-get install --assume-yes libudev-dev:$CROSS_DEB_ARCH",
    "find / -name libudev.pc",
    "echo $PKG_CONFIG_PATH",
    "PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags libudev || true",
    "ldconfig -p | grep libudev",
    "dpkg -L libudev-dev",
]
