use truncate_core::board::Direction;

use super::{tiles, TexQuad};

pub fn get_letter_quad(letter: char, orientation: Direction) -> TexQuad {
    match orientation {
        Direction::North => match letter.to_ascii_uppercase() {
            'A' => tiles::quad::LETTER_NORTH_A,
            'B' => tiles::quad::LETTER_NORTH_B,
            'C' => tiles::quad::LETTER_NORTH_C,
            'D' => tiles::quad::LETTER_NORTH_D,
            'E' => tiles::quad::LETTER_NORTH_E,
            'F' => tiles::quad::LETTER_NORTH_F,
            'G' => tiles::quad::LETTER_NORTH_G,
            'H' => tiles::quad::LETTER_NORTH_H,
            'I' => tiles::quad::LETTER_NORTH_I,
            'J' => tiles::quad::LETTER_NORTH_J,
            'K' => tiles::quad::LETTER_NORTH_K,
            'L' => tiles::quad::LETTER_NORTH_L,
            'M' => tiles::quad::LETTER_NORTH_M,
            'N' => tiles::quad::LETTER_NORTH_N,
            'O' => tiles::quad::LETTER_NORTH_O,
            'P' => tiles::quad::LETTER_NORTH_P,
            'Q' => tiles::quad::LETTER_NORTH_Q,
            'R' => tiles::quad::LETTER_NORTH_R,
            'S' => tiles::quad::LETTER_NORTH_S,
            'T' => tiles::quad::LETTER_NORTH_T,
            'U' => tiles::quad::LETTER_NORTH_U,
            'V' => tiles::quad::LETTER_NORTH_V,
            'W' => tiles::quad::LETTER_NORTH_W,
            'X' => tiles::quad::LETTER_NORTH_X,
            'Y' => tiles::quad::LETTER_NORTH_Y,
            'Z' => tiles::quad::LETTER_NORTH_Z,
            _ => unimplemented!("No texture for character {}", letter),
        },
        Direction::South => match letter.to_ascii_uppercase() {
            'A' => tiles::quad::LETTER_SOUTH_A,
            'B' => tiles::quad::LETTER_SOUTH_B,
            'C' => tiles::quad::LETTER_SOUTH_C,
            'D' => tiles::quad::LETTER_SOUTH_D,
            'E' => tiles::quad::LETTER_SOUTH_E,
            'F' => tiles::quad::LETTER_SOUTH_F,
            'G' => tiles::quad::LETTER_SOUTH_G,
            'H' => tiles::quad::LETTER_SOUTH_H,
            'I' => tiles::quad::LETTER_SOUTH_I,
            'J' => tiles::quad::LETTER_SOUTH_J,
            'K' => tiles::quad::LETTER_SOUTH_K,
            'L' => tiles::quad::LETTER_SOUTH_L,
            'M' => tiles::quad::LETTER_SOUTH_M,
            'N' => tiles::quad::LETTER_SOUTH_N,
            'O' => tiles::quad::LETTER_SOUTH_O,
            'P' => tiles::quad::LETTER_SOUTH_P,
            'Q' => tiles::quad::LETTER_SOUTH_Q,
            'R' => tiles::quad::LETTER_SOUTH_R,
            'S' => tiles::quad::LETTER_SOUTH_S,
            'T' => tiles::quad::LETTER_SOUTH_T,
            'U' => tiles::quad::LETTER_SOUTH_U,
            'V' => tiles::quad::LETTER_SOUTH_V,
            'W' => tiles::quad::LETTER_SOUTH_W,
            'X' => tiles::quad::LETTER_SOUTH_X,
            'Y' => tiles::quad::LETTER_SOUTH_Y,
            'Z' => tiles::quad::LETTER_SOUTH_Z,
            _ => unimplemented!("No texture for character {}", letter),
        },
        _ => unimplemented!("Need letter textures for direction {orientation:?}"),
    }
}
